name: circular_textfield
description: A circular textfield widget for your apps. This widget makes our TextField come as circular by default. We can also add the icon we want with the icon parameter.
version: 0.0.2
homepage: https://github.com/ilyashyrt/
repository: https://github.com/ilyashyrt/circular_textfield/
documentation: https://github.com/ilyashyrt/circular_textfield/


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

 